name: Docker Image CI
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vivekmethuku2120/angular1:latest
 
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login --username vivekmethuku2120 --password-stdin
 
    - name: Push Docker image to Docker Hub
      run: docker push vivekmethuku2120/angular1:latest
